#include "Main.h"

#include "JEngine/jrender.cpp"
#include "JEngine/jtime.cpp"
#include "JEngine/jerror.cpp"
#include "JEngine/jcollision.cpp"
#include "JEngine/jwindow.cpp"
#include "JEngine/jaudio.cpp"
#include "JEngine/jsystem.cpp"

#include "Button.cpp"
#include "Pause.cpp"
#include "Block.cpp"
#include "Cursor.cpp"
#include "Highscore.cpp"
#include "Game.cpp"
#include "GameOver.cpp"
#include "Menu.cpp"
#include "Stage.cpp"
#include "Platform.cpp"
#include "Save.cpp"
